lewagon/data-setup

- _partials/homebrew.md
- macOS.md
add `xz` & `readline` to the setup.
They are necessary to avoid the `could not import the lzma module` error forcing the reinstall of python.
> add xz & readline to setup

- LINUX.md
- WINDOWS.md
- _partials/osx_virtualenv.md
- build.rb
- macOS.md
@barangerbenjamin @gmanchon this reflects #36  suggestion to get rid of loading virtualenv from zsh but define a `global` virtualenv then `local`s virtualenvs. I also update the python version. We may go to the `3.9.0` as it is available with `pyenv`...
> Local virtualenv

- LINUX.md
- WINDOWS.md
- _partials/pip.md
- macOS.md
replace `Powershell window` with `Ubuntu terminal`
> correct terminal type in pip install instructions

- LINUX.md
- WINDOWS.md
- _partials/chrome.md
- build.rb
- macOS.md
Adding Chrome installation and setting it as default browser, related to [this issue](https://github.com/lewagon/data-challenges/issues/632) and multiple other problems resulting from Safari. 
Example: Compute Engine on GCP doesn't work properly with tools other than google (opening the new ssh connection).
Should we let the students follow the link or give explicit steps in the setup? It's pretty straightforward. WSL users should follow regular Windows installation, correct @barangerbenjamin ?
> add chrome installation

- WINDOWS.md
- _partials/homebrew.md
- macOS.md
`htop` and `tig` are not used during the bootcamp and `htop` causes setup issues
students seem to run the htop install command as root after a warning displayed by the install command. This results in a `~/.config` directory created by root and unaccessible by the user. This triggers other errors
> [macos] remove htop and tig

- WINDOWS.md
- _partials/gcp_cli_setup.md
- macOS.md
split the commands so that the install command does not get fed to the password input of the brew command
> [macos] split the gcloud CLI commands

- macOS.md
Just erased the word Ubuntu from "Ubuntu terminal" and replaced it with "Terminal"
> Erased "Ubuntu"

- LINUX.md
- WINDOWS.md
- build.rb
- macOS.md
this downgrades Python to `3.8.12` to be compliant with TF setup for M1 chips
> Fall back 38x

- WINDOWS.md
- _partials/ubuntu_docker.md
- _partials/win_docker.md
- build.rb
update the windows instructions to use Docker Desktop WSL2 backend
the Docker app can be started and stopped in Windows as in the Mac setup
the docker command is made available in Ubuntu without having to `sudo`
> use docker wsl2 backend

- LINUX.md
- WINDOWS.md
- _partials/vscode_extensions.md
- macOS.md
This is a quick fix to #79.
Better to split Windonws vs. Linux/Mac partials but lacking time to change it before Monday.
> quick fix to vs-code extensions

- build.rb
- macOS.md
- macOS_keep_current.md
This removes`tensorflow-metal` from the setup as it causes bugs when trying to train RNN. It appears RNN try to use GPU but fails.
Trace:
```
InvalidArgumentError: 2 root error(s) found.
(0) Invalid argument:  No OpKernel was registered to support Op 'CudnnRNNV3' used by {{node cond_40/then/_0/cond/CudnnRNNV3}} with these attrs: [T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm", is_training=true, seed2=0, num_proj=0, time_major=false, dropout=0, seed=0]
Registered devices: [CPU, GPU]
Registered kernels:
<no registered kernels>
[[cond_40/then/_0/cond/CudnnRNNV3]]
[[sequential_6/lstm_3/PartitionedCall]]
[[binary_crossentropy/logistic_loss/_22]]
(1) Invalid argument:  No OpKernel was registered to support Op 'CudnnRNNV3' used by {{node …
```
> remove tensorflow-metal

- LINUX.md
- WINDOWS.md
- build.rb
- macOS.md
- macOS_keep_current.md
Aligned with non-M1 version
This solves incompatibilities with pylint.
> force tensorflow-macos version below 2.6

- LINUX.md
- WINDOWS.md
- _partials/dbeaver.md
- build.rb
- macOS.md
nothing much to add to this partial at the moment
this partial is there so that the issues of future B2B students with specific setup contraints are addressed beforehand
we encountered the case of a student with a laptop unable to install DBeaver because they could not install a recent JVM
```
Incompatible JVM
Version 1.8.0_251 of the JVM is not suitable for this product. Version: 11 or greater is required.
```
note: `ruby build.rb` currently has timeouts when fetching partials from the web setup
> add dbeaver to the setup

- LINUX.md
- WINDOWS.md
- _partials/ubuntu_python.md
this 2 dependencies are required to run Facebook Prophet Python package on Ubuntu
> add python-dev dependencies for Prophet

- LINUX.md
- WINDOWS.md
- build.rb
- macOS.md
In the [22q4 web setup bug bash PR](https://github.com/lewagon/setup/pull/369), we update some partials which are used it the data setup, as you can see [here](https://github.com/lewagon/setup/pull/369/files#diff-8ce4c4af01166c2b6458748fdec5aa50a217aec720d14f28e0f3f002c095ab97):
- the `ssh_key` partial is removed and its content is updated and merged into the `gh_cli` partial
- the `git` and `zsh` partials are merged into one single `cli_tools` partials
The present PR implement the corresponding changes in the data setup build script.
> 22q4 setup bug bash

- _partials/gcp_setup_mid.md
- macOS.md
Fixes #212
I have moved the GCP credentials from `~/.aliases` to `~/.zshrc`.
Furthermore, I've added a note to advise the student to edit the line inside the `.zshrc` file if mistakes need to be fixed, rather than re-adding the corrected version of the line. This is because when debugging credentials issues, I often see students with 10+ different versions of this line inside of `.aliases`, which usually just confuses them.
> Moved GCP credentials from `~/.aliases` to `~/.zshrc`

- LINUX.es.md
- LINUX.md
- WINDOWS.es.md
- WINDOWS.md
- specs/base/package_platforms.md
- specs/base/packages.yml
- specs/constraintless/apple_intel.txt
- specs/constraintless/apple_silicon.txt
- specs/constraintless/linux.txt
- specs/generated/apple_intel.txt
- specs/generated/apple_silicon.txt
- specs/generated/linux.txt
- specs/releases/apple_intel.txt
- specs/releases/apple_silicon.txt
- specs/releases/linux.txt
Reference https://github.com/lewagon/teachers/issues/660
As mentioned by Freddy in point 6, there is no reason we should exclude Graphviz from our requirements, since it has no dependencies that aren't already fulfilled, and it works with Apple Silicon.
This package is used in the [Ensemble Method lecture](https://kitt.lewagon.com/camps/943/lectures/content/05-ML_07-Ensemble-Methods.slides.html?title=Ensemble+Methods#/1/3) to generate a graphical representation of the decision tree used throughout the lecture. The code to generate it is already in the lecture anyway, so by adding the package we ensure that they can run it themselves.
> Added Graphviz to requirements (Ensemble Methods)

- LINUX.es.md
- LINUX.md
- WINDOWS.es.md
- WINDOWS.md
- _partials/es/ubuntu_python.md
- _partials/ubuntu_python.md
fixes https://github.com/lewagon/data-setup/issues/219
I have tested on a GCE Ubuntu LTS VM, but not on a Linux or WSL machine
> remove python-dev package not available on latest ubuntu images

- WINDOWS.es.md
- WINDOWS.md
- _partials/es/win_jupyter.md
- _partials/win_jupyter.md
As there are many batches starting next week, proposing a quick fix for the issue raised by [teachers-data on Slack](https://lewagon-alumni.slack.com/archives/C015E0C601F/p1665147245366119).
* Mentioned "removing the `#` symbol" in the instruction about updating `c.NotebookApp.use_redirect_file` jupyter config
> Windows Jupyter - clarified commenting out the c.NotebookApp.use_redirect_file line

- WINDOWS.es.md
- WINDOWS.md
- checks/pip_check.sh
Reasons:
- Pandas-profiling has been remamed ydata-profiling.
- We removed it in Update apple_silicon.txt #272 from the Apple Silicon requirements, because of incompatibility with scipy
- It is a non-essential package anyway, and is used in only one challenge (04-01-03 Exploratory Analysis), which includes instructions to pip install it.
> Removing pandas-profiling from post-setup checks

- specs/releases/apple_silicon.txt
Fixes lewagon/teachers/issues/2164
Recurring setup problem on macos failing to build grpcio because wheel for 1.50.0 is not available on pypi.
Bumping to more recent version solves this.
Following packages depend on it:
- google-cloud-bigquery (but only used in taxifare, separate env)
- pandas-gbq (only used in one lecture, tested with new version: ok)
- tensorflow-macos:
- tested on CNN (challenge 1 mnist): OK
- tested on RNN (weather): OK
- in taxifare we don't fix the grpcio version so it uses most recent version and all works fine, so changing
Concluding: safe to bump this version after test on mac m1.
> Bump grpcio to 1.62.1 for Apple silicon

- LINUX.es.md
- LINUX.md
- VM.es.md
- VM.md
- WINDOWS.es.md
- WINDOWS.md
- _partials/osx_python.md
- _partials/ubuntu_python.md
- macOS.es.md
- macOS.md
Added this troubleshooting step, because during the setup it regularly occurs that pyenv is not found. Often this can be resolved by manually sourcing `.zprofile`. Reason is that some time ago pyenv was moved from `.zshrc` to `.zprofile`. `.zprofile` only gets loaded at startup, while `.zshrc` is loaded in any new terminal window, or after `exec zsh`.
Alternative would be a full restart of the computer.
> Troubleshooting pyenv not found

- LINUX.es.md
- LINUX.md
- VM.es.md
- VM.md
- WINDOWS.es.md
- WINDOWS.md
- _partials/es/gcp_setup.md
- _partials/gcp_setup.md
- macOS.es.md
- macOS.md
- Adding BigQuery fixes https://github.com/lewagon/data-challenges/issues/3309
- Compute link no longer worked
- AI Platform is deprecated (and no longer used since MLOps) and replaced by Vertex AI
> Update GCP link to enable services

- LINUX.es.md
- LINUX.md
- VM.es.md
- VM.md
- WINDOWS.es.md
- WINDOWS.md
- macOS.es.md
- macOS.md
- specs/releases/linux.txt
Setup on Windows and Ubuntu takes ages because we install gpu enabled versions of tensorflow and torch, while very few students have a gpu. Especially knowing that torch is only there for the Transformers day.
- Use tensorflow-cpu
- Specify wheel location for torch so it downloads a cpu versions
- Remove all unnecessary nvidia-cu... packages
This reduces the virtualenv size with 4 Gb!
```bash
9.4G	./lewagon
5.4G	./lwlight
```
Fixes https://github.com/lewagon/data-setup/issues/285
> Windows/Linux - Install no cuda stuff, cpu only for tf and torch

- checks/pip_check.sh
This check script is used for windows and linux as well. On these systems running ``sysctl -in sysctl.proc_translated`` can result in ``sysctl: invalid option -- 'i'``
Either way checking for m1 should only happen on macOS anyways.
> Check m1 only on macOS devices

- checks/pip_check.sh
Previously we instructed to `pip install` the
missing packages. This leads to a very different
setup than we aim for, because no version numbers
are provided.
Changed this to:
- list the packages
- instruct the students to call in a TA
- note to TA to redo the Python packages step (usually the root cause is that Apple users skipped that step)
> Pip check instructs to ask a TA for help

- LINUX.es.md
- LINUX.md
- VM.es.md
- VM.md
- WINDOWS.es.md
- WINDOWS.md
- _partials/es/kitt.md
- _partials/kitt.md
- build.rb
- macOS.es.md
- macOS.md
Web setup Kitt instructions were updated.
Web receives two emails, but DS doesn't get invited to github lewagon community.
So use a kitt partial specific for DS from now on.
> DS specific kitt partial

- specs/releases/apple_intel.txt
- specs/releases/apple_silicon.txt
- specs/releases/linux.txt
The extension has a bug: it spellchecks code cells, which is very annoying. It doesn't seem to be maintained, so we're removing it.
> Remove jupyerlab-spellchecker from the specs

- WINDOWS.es.md
- WINDOWS.md
Starting from Windows 10 2004 (May 2020 Update), WSL 2 is the default
version of WSL. The instructions for installing WSL 2 are now the same
for both Windows 10 and Windows 11.
Adapted the instructions as such, to have a common installation process.
This will:
- make the setup easier for remaining Windows 10 users,
- reduce the  number of cases where Windows 11 users started following
the Windows 10 instructions by mistake,
- make it easier to maintain the instructions in the future,
- make it easy to remove the Windows 10 instructions later.
For this we now run `wsl --install` in the Windows Command Prompt (cmd)
instead of Windows Terminal (wt, for Windows 11) or PowerShell (for
Windows 10).
For troubleshooting reasons, the instructions for Windows 10 < 2004 are
kept in details, just in …
> Align Windows 11 and 10 WSL installation

- WINDOWS.es.md
- WINDOWS.md
- _partials/es/win_vs_redistributable.md
- _partials/win_vs_redistributable.md
Currently we tell students to choose one or the other.
- This is confusing some students
- It is very unlikely to see a 32-bit system at this point
- A 32-bit Windows would only have 4 Gb of RAM, which doesn't meat our minimum requirement of 8 Gb of RAM
> Remove 32-bit C++ Redistributable
