- WINDOWS.md
- _partials/win_make.md
Remove the version to be less specific for `make`
> make less version specific

- WINDOWS.md
- _partials/win_extra.md
`handle` requires to accept EULA after first launch.
Adding a command to do so
> add eula accept command after first handle start

- LINUX.md
- WINDOWS.md
- _partials/homebrew.md
- _partials/osx_python.md
- _partials/win_extra.md
- build.rb
- macOS.md
this solves https://github.com/lewagon/data-solutions/issues/174 and brings `hub` for all
> hub for all

- LINUX.md
- WINDOWS.md
- _partials/alumni.md
- macOS.md
As of January, applicants might receive an invitation email before the start of their batch to get onboarded on kitt if the admission manager decides to do so. Therefore we added a warning message in the setup to make sure they don't onboard themselves twice on Kitt
> Add onboarding warning

- LINUX.md
- WINDOWS.md
- _partials/osx_python.md
- _partials/ubuntu_python.md
- _partials/win_python.md
- macOS.md
this removes the comment about python version from setup instructions @ssaunier please review
> remove comment

- LINUX.md
- WINDOWS.md
- _partials/pip.md
- macOS.md
this fixes #23 along with https://github.com/lewagon/dotfiles/pull/77
> add flake8 and autopep8

- .github/workflows/build_guides.yml
- LINUX.md
- WINDOWS.md
- _partials/alumni.md
- build.sh
- macOS.md
this fixes #15 @ssaunier please review
> add gha to build guides

- LINUX.md
- WINDOWS.md
- _partials/ubuntu_python.md
Probably a leftover from migrating the guide :D
> Change mac0S to Ubuntu

- _partials/osx_python.md
- macOS.md
this adds a troubleshooting section about `zlib` while installing Python with `pyenv` on OSX. @gmanchon please review
> add troubleshooting zlib

- LINUX.md
- WINDOWS.md
- macOS.md
fix https://lewagon-alumni.slack.com/archives/G02NFDT0J/p1610658793004100
> fix edge path

- LINUX.md
- WINDOWS.md
- _partials/setup_instructions.md
- build.rb
- macOS.md
Replicates the web setup update for Apple Silicon from https://github.com/lewagon/setup/pull/263
Small rewording on setup instructions
> propagate new partial from web setup for Apple Silicon computers

- LINUX.md
- WINDOWS.md
- _partials/mac_vscode.md
- _partials/osx_python.md
- _partials/osx_virtualenv.md
- _partials/ubuntu_python.md
- _partials/vscode_setup.md
- _partials/win_jupyter.md
- _partials/wsl2_vscode_settings.md
- macOS.md
> update keyboard shortcuts for macos

- LINUX.md
- WINDOWS.md
- _partials/nbextensions.md
- macOS.md
this fixes enabling of `code_prettify`
> fix install code-prettify

- LINUX.md
- WINDOWS.md
- _partials/nbextensions.md
- macOS.md
@krokrob spotted a small but important typo
> remove typo in code_prettify

- LINUX.md
- WINDOWS.md
- macOS.md
> rebuild since teamviewer removed from setup partial

- LINUX.md
- WINDOWS.md
- _partials/gcp_setup.md
- macOS.md
Following https://github.com/lewagon/data-setup/issues/82
> [gcp setup] tell part time students to skip gcp setup

- LINUX.md
- WINDOWS.md
- _partials/gcp_setup.md
- macOS.md
add a command to verify that the path to the service account json file is correctly set
> verify the path to the service account json file set in $GOOGLE_APPLICATION_CREDENTIALS

- LINUX.md
- WINDOWS.md
- _partials/nbextensions.md
- macOS.md
The env var `$JUPYTER_CONFIG_DIR` allows to define a specific conf dir for jupyter but does not seem to contain the path to the jupyter conf dir
Addresses https://github.com/lewagon/data-setup/issues/105
> correct command to cd to jupyter conf dir

- LINUX.md
- WINDOWS.md
- _partials/gcp_setup.md
- macOS.md
the goal is to facilitate the work :
- for the students to follow the instructions
- for the TA to help
> [gcp language] add instructions to set account to english

- LINUX.md
- WINDOWS.md
- _partials/pip.md
- macOS.md
this uses `data-runner` 's `requirements.txt` to install fixed version of packages
> update pip requirements with minimal packages

- checks/python_checker.sh
the python checker script was not displaying anymore the required python version
> correct checker script param

- LINUX.md
- LINUX_keep_current.md
- WINDOWS.md
- WINDOWS_keep_current.md
- _partials/keep_current.md
- _partials/pip.md
- _partials/python_checkup.md
- build.rb
- macOS.md
- macOS_keep_current.md
> install bootcamp packages and test jupyter notebook

- LINUX.md
- LINUX_keep_current.md
- WINDOWS.md
- WINDOWS_keep_current.md
- _partials/python_checkup.md
- macOS.md
- macOS_keep_current.md
> replace sh w/ zsh

- LINUX.md
- WINDOWS.md
- _partials/homebrew.md
- macOS.md
integrate the solution to the brew error raised in https://github.com/lewagon/data-setup/issues/142 into the setup
> solution for brew error encountered on old macs

- specs/releases/apple_intel.txt
- specs/releases/apple_silicon.txt
- specs/releases/linux.txt
packgenlite reference gets removed when using info from pip freeze
> correct packgenlite ref

- LINUX.md
- WINDOWS.md
- _partials/nbextensions.md
- macOS.md
this removes additional pip install because packages are already in the requirements
> remove install jupyter extensions

- LINUX.md
- WINDOWS.md
- _partials/nbextensions.md
- _partials/osx_python.md
- _partials/ubuntu_python.md
- _partials/virtualenv.md
- macOS.md
this replaces restart terminal by `exec zsh`
> replace restart by exec zsh

- specs/releases/glovebox.txt
- specs/releases/past/2022_Q1/glovebox.txt
publish glovebox packages versions into releases
> publish glovebox package versions

- LINUX.md
- WINDOWS.md
- _partials/nbextensions.md
- _partials/osx_python.md
- _partials/virtualenv.md
- macOS.md
Related to https://github.com/lewagon/setup/pull/348
> move exec zsh commands

- checks/pip_check.sh
rename bs4 to beautifulsoup
remove tensorflow-metal
remove dtale
> adapt checker.sh to new setup

- LINUX_keep_current.md
- _partials/keep_current.md
- macOS_keep_current.md
corrects the links in the keep current setup
> correct keep current requirements link

- LINUX.md
- WINDOWS.md
- build.rb
- macOS.md
> move python check after jupyter browser setup

- LINUX.md
- LINUX_keep_current.md
- WINDOWS.md
- WINDOWS_keep_current.md
- _partials/python_checkup.md
- macOS.md
- macOS_keep_current.md
Removes "that's it for today" because it was confusing
> update python checkup sentence

- LINUX.es.md
- LINUX.md
- LINUX_keep_current.es.md
- WINDOWS.es.md
- WINDOWS.md
- WINDOWS_keep_current.es.md
- build.rb
- macOS.es.md
- macOS_keep_current.es.md
add support for locales for https://github.com/lewagon/data-setup/pull/191
refacto to improve build time from 18s to 5s
the build will pass when https://github.com/lewagon/setup/pull/361 and https://github.com/lewagon/data-setup/pull/191 are merged
> multilingual build

- LINUX.md
- WINDOWS.md
- _partials/gcp_setup_linux.md
- _partials/gcp_setup_wsl.md
Related to https://github.com/lewagon/data-setup/pull/217
When I opened the PR linked above, I didn't realize I would have to also edit `gcp_setup_linux.md` and `gcp_setup_wsl.md`, as I thought that editing `gcp_setup_mid.md` would take care of it. This is now fixed!
> Fix GCP instructions for WSL and Linux

- LINUX.es.md
- LINUX.md
- WINDOWS.es.md
- WINDOWS.md
- _partials/gcp_setup.md
- _partials/ubuntu_gcloud.md
- macOS.md
update instructions to support new gcloud CLI auth flow on WSL
> WSL browser / gcloud auth login

- WINDOWS.md
- _partials/osx_silicon.md
- build.rb
- macOS.es.md
- macOS.md
add instructions to make sure that rosetta is not used
> no rosetta

- _partials/es/osx_python.md
Update translation for new data-setup
> 🇪🇸 osx_python.md

- _partials/es/direnv.md
Update translation for data-setup
> 🇪🇸 direnv.md

- _partials/es/osx_silicon.md
Update translation for data-setup
> 🇪🇸 osx_silicon.md

- checks/pip_check.sh
- specs/releases/apple_intel.txt
- specs/releases/apple_silicon.txt
- specs/releases/linux.txt
- specs/releases/past/2022_Q4/README.md
- specs/releases/past/2022_Q4/apple_intel.txt
- specs/releases/past/2022_Q4/apple_silicon.txt
- specs/releases/past/2022_Q4/linux.txt
user `tensorflow-macos` only on Apple Silicon machines
revert `pip_check.sh` to adapt the package verification
> setup 2022 q4 update

- LINUX_keep_current.es.md
- LINUX_keep_current.md
- WINDOWS_keep_current.es.md
- WINDOWS_keep_current.md
- _partials/es/keep_current.md
- _partials/keep_current.md
the command to stop docker is described as start
> setup typo

- VM.md
- build.rb
data eng content : support alternative image format in markdown
> vm setup : correct image links

- specs/releases/apple_intel.txt
- specs/releases/apple_silicon.txt
- specs/releases/linux.txt
- specs/releases/past/2022_Q4/apple_intel.txt
- specs/releases/past/2022_Q4/apple_silicon.txt
- specs/releases/past/2022_Q4/linux.txt
correct jupyter notebook yank version until the new version of the setup
> bump notebook versions

- LINUX.es.md
- LINUX.md
- VM.es.md
- VM.md
- WINDOWS.es.md
- WINDOWS.md
- _partials/es/ubuntu_python.md
- _partials/ubuntu_python.md
Removed the prompt for missing virtualenv as dotfiles changes https://github.com/lewagon/dotfiles/pull/127 removes it in order to work with data eng bootcamp without virtualenv
> Remove missing virtualenv prompt

- specs/releases/apple_intel.txt
- specs/releases/apple_silicon.txt
- specs/releases/glovebox.txt
- specs/releases/linux.txt
move to 0.0.9 so that the instructions handle correctly [pickle files in sub directories ](https://github.com/lewagon/nbresult/pull/10)
> bump nbresult version

- LINUX.md
- VM.md
- WINDOWS.md
- macOS.md
update instructions after lewagon/setup changes
> update instructions after lewagon/setup changes

- WINDOWS.es.md
- WINDOWS.md
> rebuild instructions

- LINUX.es.md
- LINUX.md
- VM.es.md
- VM.md
- WINDOWS.es.md
- WINDOWS.md
- macOS.es.md
- macOS.md
New build to pick up [these changes](https://github.com/lewagon/setup/pull/431)
> Build to update slack test instructions

- specs/releases/apple_silicon.txt
Fixes https://github.com/lewagon/data-challenges/issues/2561 (hopefully for good 🤞 )
> pip - apple silicon - bump scipy to 1.10

- specs/releases/apple_intel.txt
- specs/releases/glovebox.txt
- specs/releases/linux.txt
Updated pyyaml for all of our releases
> updated pyyaml on all releases

- WINDOWS.md
Hello @juliends 
Modification done: I removed the following sentence:
:danger: Don't install Ubuntu 18.04 LTS nor Ubuntu 20.04!
Thanks 🙏
> Update WINDOWS- remove a sentence.md

- VM.md
- checks/pip_check.sh
After updating the linux spec to tensorflow-cpu, need to update this check script too.
Maybe not the prettiest solution for now, but works. Also checked it doesn't mess up the macOS part.
> Relax pip check tf cpu

- LINUX.es.md
- LINUX.md
- VM.es.md
- VM.md
- WINDOWS.es.md
- WINDOWS.md
- _partials/dotfiles_new_laptop.md
- _partials/es/dotfiles_new_laptop.md
- macOS.es.md
- macOS.md
Mirrors lewagon/setup#467
Fixes #289
> Add note about email privacy with GitHub

- LINUX.es.md
- LINUX.md
- VM.es.md
- VM.md
- WINDOWS.es.md
- WINDOWS.md
- _partials/es/kata.md
- _partials/kata.md
- macOS.es.md
- macOS.md
Fixes https://github.com/lewagon/data-challenges/issues/3503
> Tic-Tac-Toe link

- _partials/es/osx_silicon.md
- _partials/osx_silicon.md
- macOS.es.md
- macOS.md
> OK if no rosetta box

- LINUX.es.md
- LINUX.md
- WINDOWS.es.md
- WINDOWS.md
- build.rb
- macOS.es.md
- macOS.md
Fixes #309
Almost never used, but results in many tickets.
> Remove VS Code live share

- LINUX.md
- VM.md
- WINDOWS.md
- _partials/dotfiles_new_laptop.md
- macOS.md
Fixes https://github.com/lewagon/teachers/issues/2789
> Instructions for returning student

- LINUX.md
- VM.md
- WINDOWS.md
- _partials/dotfiles_new_laptop.md
- macOS.md
This reverts commit 905a68811fe5b07eeabc751d54698ac2cd854eb2.
> Revert "Instructions for returning student (#315)"

- LINUX.md
- VM.md
- WINDOWS.md
- _partials/dotfiles_merge_upstream.md
- macOS.md
> Fix typo in dotfiles merge

- _partials/es/osx_python.md
- _partials/osx_python.md
- macOS.es.md
- macOS.md
`pyenv` does this for us. No need to do it manually anymore.
> Remove compiler flags

- LINUX.es.md
- LINUX.md
- VM.es.md
- VM.md
- WINDOWS.es.md
- WINDOWS.md
- macOS.es.md
- macOS.md
PR to bring in changes made to web setup in lewagon/setup#490
> Set SSH default in gh auth command
